short = 1
medium = 3
long = 20

# IMPORTANT! This must be preloaded with CURRENT data AND you must set requiredHistory = 0
preload = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
